### ISSUE TITLE
from confusion

### ISSUE THREAD

**Issue by thehesiod** [pgjones/flake8-sql#10]
```SQL
            SELECT year, AVG(price)
            FROM table
            WHERE table.foo=$5 AND table.bar=$6 AND
                table.day >= ($3::DATE + ((extract(year from table."day") - 2 || ' year')::INTERVAL))::DATE AND
```

and get errors like: `Q447 root_keywords FROM and from are not right aligned`

presumably due to the `year from table` section

**Comment by pgjones** [comment]
This should be fixed by d1a1000e870db0c3fd88cf5e5c7a62c33aad51d8 and released in 0.4.0
