### ISSUE TITLE
The syntax for disabling multiple warnings in one line is too strict

### ISSUE THREAD

**Issue by mikhaildubov** [pgjones/flake8-sql#6]
As of now, the `# noqa: ...` statement disables only the first warning when the corresponding codes are separated by `', '` (with a space), e.g. the following will only disable `Q440`:

`# noqa: Q440, Q447, Q448, Q449`

-- which might be confusing if you don't know that spaces are not allowed (they probably should be). The following still disables all the warnings:

`# noqa: Q440,Q447,Q448,Q449`

**Comment by pgjones** [comment]
This is something that is fixed in flake8, [recently](https://gitlab.com/pycqa/flake8/commit/ec996ffd85cbe6157b7cf480e7c84b36d2153f4b), so presumably on that release you can use spaces.
